### ISSUE TITLE
boost configuration failed build error

### ISSUE THREAD

**Issue by anand-010** [weinzierl-engineering/baos#21]
I've tried to build baos on linux but i've stuck on this error.
```
/home/anand/Desktop/baos-18.2.0/kdrive/include/kdrive/utility/PropertyCollection.h:19:10: fatal error: boost/signals2.hpp: No such file or directory
 #include <boost/signals2.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
i've downloaded [boost_1_80_0.tar.gz](https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz) and extracted it to the project dir.
and also tried to clone 
https://github.com/boostorg/signals2.
but i've still got the error.

What is the folder structure for correct installation of this lib?.

**Comment by weinzierl-engineering** [comment]
Hello anand-010,

the problem is that the project cannot find the Boost header files.

Solution 1:

The boost files have been extracted somewhere.
e.g. ./path/to/boost/boost_1_XX_Y
(The file LICENSE_1_0.txt is then under ./path/to/boost/boost_1_XX_Y/LICENSE_1_0.txt)

Then use the variable BOOST_ROOT to specify the root path to Boost:
cmake -DBOOST_ROOT=./path/to/boost/boost_1_XX_Y -DCMAKE_BUILD_TYPE=Release -DWZSDK_STATIC=1 -DWZSDK_SAMPLES=1 -DWZSDK_SAMPLES_QT=0 -G "Unix Makefiles" ../


Solution 2:

Alternatively, boost can also be installed (in system path)

e.g. for Ubuntu:
apt-get install libboost-dev

Then the include should also be found.

cmake -DCMAKE_BUILD_TYPE=Release -DWZSDK_STATIC=1 -DWZSDK_SAMPLES=1 -DWZSDK_SAMPLES_QT=0 -G "Unix Makefiles" ../

For comments or questions please feel free to contact us.

Best regards,
Weinzierl Engineering GmbH
